name: Translate Asset Titles

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 22.x

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/learningpathways/v4/en-us/assets.json'
  pull_request:
    paths:
      - 'docs/learningpathways/v4/en-us/assets.json'
  
jobs:
  replace-localization:
    name: Replace localization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo codebase
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '.github/workflows/scripts/package-lock.json'
      - name: Install dependencies
        working-directory: .github/workflows/scripts
        run: npm ci
      - name: Run translation script
        run: node .github/workflows/scripts/translateAssets.js
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create Pull Request
        uses: actions/create-pull-request@v5
        with:
          commit-message: "Update languages assets based on a change to the English Version"
          title: "[Automated PR] Update languages assets"
          body: |
            This PR was automatically generated to update the localized asset titles based on changes made to the English version of the assets.
    
