name: Translate Asset Titles

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 22.x

on:
  workflow_dispatch:



jobs:
  replace-localization:
    name: Replace localization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo codebase
        uses: actions/checkout@v4
        with:
          clean: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: |
              sudo npm install axios --global
              sudo npm install cheerio --global
              sudo npm install fs --global
              sudo npm install express --global
      - name: Run translation script
        run: node .github/workflows/scripts/translateAssets.js
      - name: Commit changes
        run: |
          git add -A
          git commit -m "Updated localized asset titles"
          git push
