name: Translate Asset Titles
run-name: ${{ github.actor }} is translating the assets.json file for other languages
on:
  push:
    paths:
      - 'docs/learningpathways/v4/en-us/assets.json'
  pull_request:
    paths:
      - 'docs/learningpathways/v4/en-us/assets.json'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: content='docs/learningpathways/v4/en-us/assets.json'
      - run: for asset in ${{ fromJSON('docs/learningpathways/v4/en-us/assets.json') }}
      - run: do
      - run: echo asset.url
      - run: done
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
